### ISSUE TITLE
Could you please share your training code?

### ISSUE THREAD

**Issue by sqiangcao99** [papermsucode/mdmmt#2]

**Comment by sqiangcao99** [comment]
Hi. Thanks for generously sharing your code. Could you please share your training code. It will be easy for us to reproduce the results.

**Comment by VlaDanilov** [comment]
> Hi. Thanks for generously sharing your code. Could you please share your training code. It will be easy for us to reproduce the results.
Hello, did you get the training code? Could you please share it?
