### ISSUE TITLE
Can you please explain the function prepare_features?

### ISSUE THREAD

**Issue by AnaRhisT94** [papermsucode/mdmmt#4]
How do u prepare the features of vgg, video and clip with this function?
Do u skip on frames or cut some of them?
how do u combine everything with bertvid?

From what I saw when I have for e.g. over 30 frames (of clip embeddings) you just take only the first 30. what happens to the other frames?

**Comment by dzabraev** [comment]
This repository does not have a function "prepare_features".

For testing we take first 30 features. If u wanna deploy this model u can split long input to segments, where each segment has 30 frames length.

To combine embeddings from three modalities (clip, vmz, sound-model) we do following steps. 

Suppose clip produced sequence of embeddings x1, ..., x30; vmz produced y1,...,y30; sound model: z1,...,z30. We construct sequence like [clip-cls] x1 ... x30 [vmz-cls] y1 ... y30 [sound-cls] z1 ... z30 and then just feed it to transformer encoder. Then we take the output from three cls tokens and concatenate them. This is the final embedding.
